version: "3.1"

services:
  pgdb:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: taNo123!@#taNo
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-admin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: huynhminhtan12792@gmail.com
      PGADMIN_DEFAULT_PASSWORD: taNo123!@#taNo
